site_name: Ø¢Ù…ÙˆØ²Ø´ Ù‡Ø§

theme:
  name: 'material'
  language: 'fa'
  direction: 'rtl'
  palette:
    primary: 'green'
    accent: 'blue'
  font: false
  feature:
    tabs: false
    
  features:
    - search.suggest
    - search.highlight
    - navigation.top
    - content.code.copy
    - content.action.edit  
    
    
  # extra:
  #   social:
  #     - type: 'github'
  #       link: 'https://github.com/squidfunk'    

extra_css:
  - 'stylesheets/extra.css'
  - CSS/pdf.css

nav:
- Ø¢Ù…ÙˆØ²Ø´ Ú¯ÛŒØª: 'index.md'
- Ø¢Ù…ÙˆØ²Ø´ Ø¯Ø§Ú©Ø±: 'docker.md'
#- Ø¨Ø®Ø´ Ø¯Ùˆ: 'sec2.md'

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - attr_list
  - md_in_html
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: ðŸ”—
      # title: On this page
      permalink_title: Link here

plugins:
    - search:
        indexing: 'full'
          #    - pdf-export:
          #        verbose: true
          #        media_type: print
    - glightbox:
        zoomable: true

repo_url: http://git.ft/doc/documents
edit_uri: edit/main/docs/
